version: "3.7"

services:
  n8n:
    image: n8nio/n8n:latest  # Sempre usarà la darrera versió estable
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
    volumes:
      - /home/node/.n8n  # Aquest serà el volum de Railway (no cal especificar res local)

